---
title: "Chaff"
author: "Daniel Sproston"
date: "04/11/2020"
output:
  bookdown::html_document2: default
  bookdown::word_document2: default
  bookdown::pdf_document2: default
bibliography: Bioenterprise.bib
---

##Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE,
                      fig.retina = 3)
```

```{r packages}
library(tidyverse)
library(magrittr)
library(dplyr)
library(tidyr)
library(readr)
library(tibble)
library(stringr)
library(forcats)
library(janitor)
library(multiway)
library(citr)
library(kableExtra)
library(flextable)
library(gt)
library(bibtex)
```

```{r Data}
setwd("~/University/Data Analysis Y4/chaffworkshop")
chaff1 <- read.table("chaff.txt", header = T) 
```

# Introduction
Just ramble on this unscientific, hard to reference article,  [@European_Patent_Office_undated-ek]

```{r Data tidy}
chaff <- gather(data = chaff1, key = "sex", value = "mass")
```


```{r Data mass}
sum(chaff$mass)
```

```{r Data SSx}
 sum_sq <- function(df, measure) {
  df %>% summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

sum_sq(chaff, mass)
```
```{r Data SSx extra}
sum_sq <- function(df, measure, group) {
  df %>% group_by({{ group }}) %>% 
    summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

sum_sq(chaff, mass, sex)
```

```{r Data table}
ggplot(data = chaff, aes(x = sex, y = mass)) +
  geom_bar(stat = "identity")
```


## Reference